### ISSUE TITLE
raise CalledProcessError(retcode, cmd)

### ISSUE THREAD

**Issue by weaming** [keakon/Doodle#3]
```
2016-02-28 23:13:35 (144 MB/s) - `bootstrap-buildout.py' saved [7458/7458]

Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.2.2.zip
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 123, in _do_download
  File "<string>", line 336, in download_setuptools
  File "<string>", line 255, in download_file_curl
  File "<string>", line 210, in _clean_check
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-20.2.2.zip', '--silent', '--output', '/www/doodle/downloads/setuptools-20.2.2.zip']' returned non-zero exit status 23
scripts/buildout.sh: line 8: bin/buildout: No such file or directory

```

**Comment by keakon** [comment]
看上去像是你没有给写权限。

> CURLE_WRITE_ERROR (23)
> An error occurred when writing received data to a local file, or an error was returned to libcurl from a write callback.

确认一下 `/www/doodle/downloads/` 的写入权限。

**Comment by weaming** [comment]
@keakon 我以root权限运行的

**Comment by keakon** [comment]
我知道了，创建的文件夹名字写错了，应该是 `downloads`，写成了 `download`。

**Comment by weaming** [comment]
@keakon 手动斜眼

**Comment by weaming** [comment]
shell 哪里有问题。。。

```
Develop: '/www/doodle/.'
Traceback (most recent call last):
  File "/tmp/tmpT3I7et", line 14, in <module>
    exec(compile(f.read(), '/www/doodle/./setup.py', 'exec'))
  File "/www/doodle/./setup.py", line 27, in <module>
    install()
  File "/www/doodle/./scripts/install.py", line 67, in install
    link_config()
  File "/www/doodle/./scripts/install.py", line 30, in link_config
    for conf_name in os.listdir(private_conf_dir):
OSError: [Errno 2] No such file or directory: '/www/doodle/./scripts/../private/conf'
While:
  Installing.
  Processing develop directory '/www/doodle/.'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/www/doodle/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/www/doodle/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/www/doodle/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/www/doodle/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 1020, in develop
    call_subprocess(args)
  File "/www/doodle/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/usr/bin/python', '/tmp/tmpT3I7et', '-q', 'develop', '-mN', '-d', '/www/doodle/develop-eggs/tmpbOrS8xbuild'

```

**Comment by keakon** [comment]
其实是让你在 private 文件夹里放自己的私有配置，安装时会 link 到真实路径。我是把配置放在另一个仓库，然后 clone 到 private 文件夹。

**Comment by weaming** [comment]
@keakon 不懂，已经用go语言生成了静态博客 https://wowapi.org
- 方便
- markdown
- 可定制
- 无数据库
